print("Hello students")
print("Ar čia galima rašyti?")
print("Hello from Ernestas!")
print('Hello from Jonas!')
print("Hello from Martynas!")
print("Hello from Andrius!")
print("Hello from Monika")
print("Hello from Egle")
print("Hello from Darius")
print("Hello from Tomas")
print("Hello from Rolandas!")
print('Hello from Robertas')
